using System.Collections;
using System.Collections.Generic;
using UnityEngine;
using Normal.Realtime;
using Normal.Realtime.Serialization;

[RealtimeModel]
public partial class BoolSyncModel {
    [RealtimeProperty(10, true, true)]
    private bool _activationBool;
}

/* ----- Begin Normal Autogenerated Code ----- */
public partial class BoolSyncModel : RealtimeModel {
    public bool activationBool {
        get {
            return _activationBoolProperty.value;
        }
        set {
            if (_activationBoolProperty.value == value) return;
            _activationBoolProperty.value = value;
            InvalidateReliableLength();
            FireActivationBoolDidChange(value);
        }
    }
    
    public delegate void PropertyChangedHandler<in T>(BoolSyncModel model, T value);
    public event PropertyChangedHandler<bool> activationBoolDidChange;
    
    public enum PropertyID : uint {
        ActivationBool = 10,
    }
    
    #region Properties
    
    private ReliableProperty<bool> _activationBoolProperty;
    
    #endregion
    
    public BoolSyncModel() : base(null) {
        _activationBoolProperty = new ReliableProperty<bool>(10, _activationBool);
    }
    
    protected override void OnParentReplaced(RealtimeModel previousParent, RealtimeModel currentParent) {
        _activationBoolProperty.UnsubscribeCallback();
    }
    
    private void FireActivationBoolDidChange(bool value) {
        try {
            activationBoolDidChange?.Invoke(this, value);
        } catch (System.Exception exception) {
            UnityEngine.Debug.LogException(exception);
        }
    }
    
    protected override int WriteLength(StreamContext context) {
        var length = 0;
        length += _activationBoolProperty.WriteLength(context);
        return length;
    }
    
    protected override void Write(WriteStream stream, StreamContext context) {
        var writes = false;
        writes |= _activationBoolProperty.Write(stream, context);
        if (writes) InvalidateContextLength(context);
    }
    
    protected override void Read(ReadStream stream, StreamContext context) {
        var anyPropertiesChanged = false;
        while (stream.ReadNextPropertyID(out uint propertyID)) {
            var changed = false;
            switch (propertyID) {
                case (uint) PropertyID.ActivationBool: {
                    changed = _activationBoolProperty.Read(stream, context);
                    if (changed) FireActivationBoolDidChange(activationBool);
                    break;
                }
                default: {
                    stream.SkipProperty();
                    break;
                }
            }
            anyPropertiesChanged |= changed;
        }
        if (anyPropertiesChanged) {
            UpdateBackingFields();
        }
    }
    
    private void UpdateBackingFields() {
        _activationBool = activationBool;
    }
    
}
/* ----- End Normal Autogenerated Code ----- */
