using System.Collections;
using System.Collections.Generic;
using UnityEngine;
using Normal.Realtime;
using Normal.Realtime.Serialization;

[RealtimeModel]
public partial class DeviceSyncModel
{
    [RealtimeProperty(31, true, true)]
    private int _deviceType;
}

/* ----- Begin Normal Autogenerated Code ----- */
public partial class DeviceSyncModel : RealtimeModel {
    public int deviceType {
        get {
            return _deviceTypeProperty.value;
        }
        set {
            if (_deviceTypeProperty.value == value) return;
            _deviceTypeProperty.value = value;
            InvalidateReliableLength();
            FireDeviceTypeDidChange(value);
        }
    }
    
    public delegate void PropertyChangedHandler<in T>(DeviceSyncModel model, T value);
    public event PropertyChangedHandler<int> deviceTypeDidChange;
    
    public enum PropertyID : uint {
        DeviceType = 31,
    }
    
    #region Properties
    
    private ReliableProperty<int> _deviceTypeProperty;
    
    #endregion
    
    public DeviceSyncModel() : base(null) {
        _deviceTypeProperty = new ReliableProperty<int>(31, _deviceType);
    }
    
    protected override void OnParentReplaced(RealtimeModel previousParent, RealtimeModel currentParent) {
        _deviceTypeProperty.UnsubscribeCallback();
    }
    
    private void FireDeviceTypeDidChange(int value) {
        try {
            deviceTypeDidChange?.Invoke(this, value);
        } catch (System.Exception exception) {
            UnityEngine.Debug.LogException(exception);
        }
    }
    
    protected override int WriteLength(StreamContext context) {
        var length = 0;
        length += _deviceTypeProperty.WriteLength(context);
        return length;
    }
    
    protected override void Write(WriteStream stream, StreamContext context) {
        var writes = false;
        writes |= _deviceTypeProperty.Write(stream, context);
        if (writes) InvalidateContextLength(context);
    }
    
    protected override void Read(ReadStream stream, StreamContext context) {
        var anyPropertiesChanged = false;
        while (stream.ReadNextPropertyID(out uint propertyID)) {
            var changed = false;
            switch (propertyID) {
                case (uint) PropertyID.DeviceType: {
                    changed = _deviceTypeProperty.Read(stream, context);
                    if (changed) FireDeviceTypeDidChange(deviceType);
                    break;
                }
                default: {
                    stream.SkipProperty();
                    break;
                }
            }
            anyPropertiesChanged |= changed;
        }
        if (anyPropertiesChanged) {
            UpdateBackingFields();
        }
    }
    
    private void UpdateBackingFields() {
        _deviceType = deviceType;
    }
    
}
/* ----- End Normal Autogenerated Code ----- */
