using System.Collections;
using System.Collections.Generic;
using UnityEngine;
using Normal.Realtime;
using Normal.Realtime.Serialization;

[RealtimeModel]
public partial class IntSyncModel {
    [RealtimeProperty(4, true, true)]
    private int _dropdownInt;
}

/* ----- Begin Normal Autogenerated Code ----- */
public partial class IntSyncModel : RealtimeModel {
    public int dropdownInt {
        get {
            return _dropdownIntProperty.value;
        }
        set {
            if (_dropdownIntProperty.value == value) return;
            _dropdownIntProperty.value = value;
            InvalidateReliableLength();
            FireDropdownIntDidChange(value);
        }
    }
    
    public delegate void PropertyChangedHandler<in T>(IntSyncModel model, T value);
    public event PropertyChangedHandler<int> dropdownIntDidChange;
    
    public enum PropertyID : uint {
        DropdownInt = 4,
    }
    
    #region Properties
    
    private ReliableProperty<int> _dropdownIntProperty;
    
    #endregion
    
    public IntSyncModel() : base(null) {
        _dropdownIntProperty = new ReliableProperty<int>(4, _dropdownInt);
    }
    
    protected override void OnParentReplaced(RealtimeModel previousParent, RealtimeModel currentParent) {
        _dropdownIntProperty.UnsubscribeCallback();
    }
    
    private void FireDropdownIntDidChange(int value) {
        try {
            dropdownIntDidChange?.Invoke(this, value);
        } catch (System.Exception exception) {
            UnityEngine.Debug.LogException(exception);
        }
    }
    
    protected override int WriteLength(StreamContext context) {
        var length = 0;
        length += _dropdownIntProperty.WriteLength(context);
        return length;
    }
    
    protected override void Write(WriteStream stream, StreamContext context) {
        var writes = false;
        writes |= _dropdownIntProperty.Write(stream, context);
        if (writes) InvalidateContextLength(context);
    }
    
    protected override void Read(ReadStream stream, StreamContext context) {
        var anyPropertiesChanged = false;
        while (stream.ReadNextPropertyID(out uint propertyID)) {
            var changed = false;
            switch (propertyID) {
                case (uint) PropertyID.DropdownInt: {
                    changed = _dropdownIntProperty.Read(stream, context);
                    if (changed) FireDropdownIntDidChange(dropdownInt);
                    break;
                }
                default: {
                    stream.SkipProperty();
                    break;
                }
            }
            anyPropertiesChanged |= changed;
        }
        if (anyPropertiesChanged) {
            UpdateBackingFields();
        }
    }
    
    private void UpdateBackingFields() {
        _dropdownInt = dropdownInt;
    }
    
}
/* ----- End Normal Autogenerated Code ----- */
