using System.Collections;
using System.Collections.Generic;
using UnityEngine;
using Normal.Realtime;
using Normal.Realtime.Serialization;

[RealtimeModel]
public partial class NameSyncModel
{
    [RealtimeProperty(20, true, true)]
    private string _userName;
}

/* ----- Begin Normal Autogenerated Code ----- */
public partial class NameSyncModel : RealtimeModel {
    public string userName {
        get {
            return _userNameProperty.value;
        }
        set {
            if (_userNameProperty.value == value) return;
            _userNameProperty.value = value;
            InvalidateReliableLength();
            FireUserNameDidChange(value);
        }
    }
    
    public delegate void PropertyChangedHandler<in T>(NameSyncModel model, T value);
    public event PropertyChangedHandler<string> userNameDidChange;
    
    public enum PropertyID : uint {
        UserName = 20,
    }
    
    #region Properties
    
    private ReliableProperty<string> _userNameProperty;
    
    #endregion
    
    public NameSyncModel() : base(null) {
        _userNameProperty = new ReliableProperty<string>(20, _userName);
    }
    
    protected override void OnParentReplaced(RealtimeModel previousParent, RealtimeModel currentParent) {
        _userNameProperty.UnsubscribeCallback();
    }
    
    private void FireUserNameDidChange(string value) {
        try {
            userNameDidChange?.Invoke(this, value);
        } catch (System.Exception exception) {
            UnityEngine.Debug.LogException(exception);
        }
    }
    
    protected override int WriteLength(StreamContext context) {
        var length = 0;
        length += _userNameProperty.WriteLength(context);
        return length;
    }
    
    protected override void Write(WriteStream stream, StreamContext context) {
        var writes = false;
        writes |= _userNameProperty.Write(stream, context);
        if (writes) InvalidateContextLength(context);
    }
    
    protected override void Read(ReadStream stream, StreamContext context) {
        var anyPropertiesChanged = false;
        while (stream.ReadNextPropertyID(out uint propertyID)) {
            var changed = false;
            switch (propertyID) {
                case (uint) PropertyID.UserName: {
                    changed = _userNameProperty.Read(stream, context);
                    if (changed) FireUserNameDidChange(userName);
                    break;
                }
                default: {
                    stream.SkipProperty();
                    break;
                }
            }
            anyPropertiesChanged |= changed;
        }
        if (anyPropertiesChanged) {
            UpdateBackingFields();
        }
    }
    
    private void UpdateBackingFields() {
        _userName = userName;
    }
    
}
/* ----- End Normal Autogenerated Code ----- */
