using System.Collections;
using System.Collections.Generic;
using UnityEngine;
using Normal.Realtime;
using Normal.Realtime.Serialization;

[RealtimeModel]
public partial class StringSyncModel
{
    [RealtimeProperty(13, true, true)]
    private string _text = "";
}


/* ----- Begin Normal Autogenerated Code ----- */
public partial class StringSyncModel : RealtimeModel {
    public string text {
        get {
            return _textProperty.value;
        }
        set {
            if (_textProperty.value == value) return;
            _textProperty.value = value;
            InvalidateReliableLength();
            FireTextDidChange(value);
        }
    }
    
    public delegate void PropertyChangedHandler<in T>(StringSyncModel model, T value);
    public event PropertyChangedHandler<string> textDidChange;
    
    public enum PropertyID : uint {
        Text = 13,
    }
    
    #region Properties
    
    private ReliableProperty<string> _textProperty;
    
    #endregion
    
    public StringSyncModel() : base(null) {
        _textProperty = new ReliableProperty<string>(13, _text);
    }
    
    protected override void OnParentReplaced(RealtimeModel previousParent, RealtimeModel currentParent) {
        _textProperty.UnsubscribeCallback();
    }
    
    private void FireTextDidChange(string value) {
        try {
            textDidChange?.Invoke(this, value);
        } catch (System.Exception exception) {
            UnityEngine.Debug.LogException(exception);
        }
    }
    
    protected override int WriteLength(StreamContext context) {
        var length = 0;
        length += _textProperty.WriteLength(context);
        return length;
    }
    
    protected override void Write(WriteStream stream, StreamContext context) {
        var writes = false;
        writes |= _textProperty.Write(stream, context);
        if (writes) InvalidateContextLength(context);
    }
    
    protected override void Read(ReadStream stream, StreamContext context) {
        var anyPropertiesChanged = false;
        while (stream.ReadNextPropertyID(out uint propertyID)) {
            var changed = false;
            switch (propertyID) {
                case (uint) PropertyID.Text: {
                    changed = _textProperty.Read(stream, context);
                    if (changed) FireTextDidChange(text);
                    break;
                }
                default: {
                    stream.SkipProperty();
                    break;
                }
            }
            anyPropertiesChanged |= changed;
        }
        if (anyPropertiesChanged) {
            UpdateBackingFields();
        }
    }
    
    private void UpdateBackingFields() {
        _text = text;
    }
    
}
/* ----- End Normal Autogenerated Code ----- */
