using System.Collections;
using System.Collections.Generic;
using UnityEngine;
using Normal.Realtime;
using Normal.Realtime.Serialization;

[RealtimeModel]
public partial class TitleSyncModel
{
    [RealtimeProperty(33, true, true)]
    private string _title;
}

/* ----- Begin Normal Autogenerated Code ----- */
public partial class TitleSyncModel : RealtimeModel {
    public string title {
        get {
            return _titleProperty.value;
        }
        set {
            if (_titleProperty.value == value) return;
            _titleProperty.value = value;
            InvalidateReliableLength();
            FireTitleDidChange(value);
        }
    }
    
    public delegate void PropertyChangedHandler<in T>(TitleSyncModel model, T value);
    public event PropertyChangedHandler<string> titleDidChange;
    
    public enum PropertyID : uint {
        Title = 33,
    }
    
    #region Properties
    
    private ReliableProperty<string> _titleProperty;
    
    #endregion
    
    public TitleSyncModel() : base(null) {
        _titleProperty = new ReliableProperty<string>(33, _title);
    }
    
    protected override void OnParentReplaced(RealtimeModel previousParent, RealtimeModel currentParent) {
        _titleProperty.UnsubscribeCallback();
    }
    
    private void FireTitleDidChange(string value) {
        try {
            titleDidChange?.Invoke(this, value);
        } catch (System.Exception exception) {
            UnityEngine.Debug.LogException(exception);
        }
    }
    
    protected override int WriteLength(StreamContext context) {
        var length = 0;
        length += _titleProperty.WriteLength(context);
        return length;
    }
    
    protected override void Write(WriteStream stream, StreamContext context) {
        var writes = false;
        writes |= _titleProperty.Write(stream, context);
        if (writes) InvalidateContextLength(context);
    }
    
    protected override void Read(ReadStream stream, StreamContext context) {
        var anyPropertiesChanged = false;
        while (stream.ReadNextPropertyID(out uint propertyID)) {
            var changed = false;
            switch (propertyID) {
                case (uint) PropertyID.Title: {
                    changed = _titleProperty.Read(stream, context);
                    if (changed) FireTitleDidChange(title);
                    break;
                }
                default: {
                    stream.SkipProperty();
                    break;
                }
            }
            anyPropertiesChanged |= changed;
        }
        if (anyPropertiesChanged) {
            UpdateBackingFields();
        }
    }
    
    private void UpdateBackingFields() {
        _title = title;
    }
    
}
/* ----- End Normal Autogenerated Code ----- */
